server:
  servlet:
    encoding:
      force-response: true

#application-oauth.yml 추가
spring:
  profiles:
    include: oauth, db

  resources:
    static-locations: classpath:/static/
#h2 database
#  h2:
#    console:
#      enabled: true


#jpa
  jpa:
    showSql: true

    hibernate:
      ddlAuto: update

#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
#
#    username: sa
#    password: password